#!/bin/zsh

# HomeBrew: Set PATH, MANPATH, etc.,
eval "$(/opt/homebrew/bin/brew shellenv)"
export EDITOR='nvim'
export VEDITOR='code'

# Spaceship
source "${HOME}/.zsh/spaceship/spaceship.zsh"
fpath=("$HOMEBREW_PREFIX/share/zsh/site-functions" $fpath)
autoload -U promptinit; promptinit
# prompt spaceship

# ASDF
. ${HOME}/.asdf/asdf.sh
# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

# bindkey
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

# Environment variables
export PATH=${HOME}/bin:${PATH}
export PROJECTS="$HOME/Code"

# fzf completion and binding
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Sourcegraph
export SRC_ENDPOINT="https://checkr.sourcegraph.com/"

# Teleport
export TELEPORT_PROXY="heimdallr.checkrhq.net"
export TELEPORT_AUTH="gitlab"

# zsh
source $HOME/.zsh/completion.zsh
source $HOME/.zsh/alias.zsh

# Post shell notification
gecho -e "Run 'okteto context use' if you want to start using okteto"
gecho -e "Set 'SRC_ACCESS_TOKEN' to use src-cli"
